apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-api
  labels:
    app: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: scottdkey/basic-api:1.0.1
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "128Mi"
              cpu: "0.4"
