apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-api
  labels:
    app: basic
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app: basic
  template:
    metadata:
      labels:
        app: basic
    spec:
      containers:
        - name: basic
          image: scottdkey/basic-api
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "64Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "600m"
