apiVersion: apps/v1
kind: Deployment
metadata:  
  name: basic-api
  labels:    
    app: helloworld
spec:  
  replicas: 1  
  selector:    
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec: 
     containers:
      - name: helloworld
        image: scottdkey/basic-api:1.0.0
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: basic-api-service
  labels:
    app: helloworld
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
    nodePort: 32121
  selector:
    app: helloworld