# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  on-success:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set kube context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeConfig: ${{ secrets.KUBECONFIG }}

      - name: Update deployment
        uses: Azure/k8s-deploy@v1.4
        with:
          namespace: "default"
          manifests: |
            deployment.yaml
            service.yaml
          images: ghcr.scottdkey/basic-api:${{ github.sha }}
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo "First workflow was a failure"
